language: generic

sudo: false

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create --name ioamdocenv
  - source activate ioamdocenv
  - conda install -c ioam -c bokeh -c conda-forge -c defaults python=3.6* paramnb numpy scipy notebook matplotlib pandas bokeh=0.12.10 nose networkx xarray datashader scikit-image selenium phantomjs streamz=0.2.0 dask=0.15.4 sphinx runipy beautifulsoup4 graphviz plotly holoviews
  # worked on my mac, doesn't work on linux; bail on conda pkg til figure out recipe :(
  #- conda install -c cball -c ioam -c bokeh -c conda-forge nbsite
  - conda remove --force holoviews
  - pip install -e .
  - pip install nbsite
  - pip install sphinx_ioam_theme

before_script:
  # copied from https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3;
    fi

script:
  - export THISPROJECT=holoviews
  - export THISMODULE=holoviews
  - mkdir doc
  - cd doc
  - nbsite_from_tmplate.py .
  ##########################################################  
  # "make gallery"
  - nbsite_gallery.py ../
  ##########################################################  
  # "make refmanual"
  - nbsite_generate_modules.py ${THISMODULE} -d ./Reference_Manual -n ${THISPROJECT} -e tests
  ##########################################################
  # "make ipynb-rst"
  - nbsite_nbpagebuild.py continuumio ${THISPROJECT} ../examples .
  ##########################################################
  # "make html"
  - sphinx-build -b html . ./_build/html
  ##########################################################
  # "make fix-links"
  - nbsite_fix_links.py _build/html
  - touch ./_build/html/.nojekyll
  - nbsite_cleandisthtml.py ./_build/html take_a_chance

deploy:
  provider: pages
  repo: ceball/ceball.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./_build/html
  on:
    branch: tmphvdocs
