language: generic

sudo: false

install:
  - wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O anaconda.sh;
  - bash anaconda.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -f doc/builder/ioamdocenv.yml
  - source activate ioamdocenv
  - cd doc/builder/ioam_theme && python setup.py install && cd ../../..  

script:
  - export PYTHONPATH=$PWD/doc
  - cd doc
  - cp builder/tmplate/*.rst .
  - cp builder/tmplate/*.html .
  - cp builder/tmplate/*.py .
  - cp builder/tmplate/Makefile .
  - mkdir user_guide
  - cp builder/tmplate/user_guide/index.rst user_guide/
  - mkdir getting_started
  - cp builder/tmplate/getting_started/index.rst getting_started/
  - make gallery
  - make refmanual
  - make ipynb-rst
  - make html
  - make fix-links
  - touch ./_build/html/.nojekyll

deploy:
  provider: pages
  repo: ceball/ceball.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./_build/html
  on:
    branch: tmphvdocs
